version: "3.7"
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./config/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  Postgres:
    image: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: always
    networks:
      - db-network
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=user_ro
      - POSTGRES_PASSWORD=4r2w3e1q
      - POSTGRES_DB=freader
    ports:
      - "5432:5432"
networks:
  db-network:
    driver: bridge
volumes:
  postgres_data: