version: "3"
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./config/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=readerXML
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodb_data_container:/data/db

  Postgres:
    image: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: always
    networks:
      - db-network
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=user_ro
      - POSTGRES_PASSWORD=4r2w3e1q
      - POSTGRES_DB=freader
    ports:
      - "5432:5432"
networks:
  db-network:
    driver: bridge
volumes:
  postgres_data:
  mongodb_data_container: