[MainSettings]
server_connect = "127.0.0.1:8080"
log_level = "debug"

[Directory]
root_path = "/fcs_regions"
main_folder = "/Files"

[Tasks]
notifications44 = 1
notifications223 = 1
protocols44 = 8
protocols223 = 11

[Rabbit]
connection_rabbit = "amqp://guest:guest@rabbitmq:5672/"

[FTPServer44]
username = "free"
password = "free"
url44 = "ftp.zakupki.gov.ru:21"
root_path = "/fcs_regions"

[FTPServer223]
username = "fz223free"
password = "fz223free"
url44 = "ftp.zakupki.gov.ru:21"
root_path = "/out/published"

[Postgres]
host     = "Postgres"
port     = 5432
user     = "user_ro"
password = "4r2w3e1q"
dbname   = "freader"